version: '3.7'

services:

  sample:
    container_name: projet_secu
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  # mariadb:
  #   image: mariadb
  #   restart: always
  #   environment: 
  #     MYSQL_ROOT_PASSWORD: secret
  #   volumes: 
  #     - ./data:/var/lib/mysql
  #   ports: 
  #     - 3306:3306